### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by christiancompton** [IBM/weather-forecasting-ios#1]
This code will not compile.  Please regenerate using Apple Console Weather project.

The only addition the README needs is the language below with an updated link. 
> As an alternative to steps 1 & 2 below, you can create this project as a starter kit on IBM Cloud, which automatically provisions required services, and injects service credentials into a custom fork of this pattern. Then, you can skip directly to step 3 below.

**Comment by dolph** [comment]
I believe I also generated these two repos through the mobile console:

https://github.com/IBM/visual-recognition-ios
https://github.com/IBM/tone-analyzer-ios

I assume this issue affects those repos as well?

**Comment by dolph** [comment]
Regenerated in https://github.com/IBM/weather-forecasting-ios/commit/07528279123e468314c13da6870d6748769875e9
