### ISSUE TITLE
Missing Android example

### ISSUE THREAD

**Issue by derekteay** [IBM/weather-forecasting-ios#7]
The readme says "We have a similar pattern available for Android, as well!" however that link (https://github.com/IBM/weather-forecasting-android) doesn't seem to exists. Searching all of the repos in the IBM org don't seem to show the proper example.

**Comment by stevemar** [comment]
eek, that was done preemptively when we were porting the android starter kit over, but noticed issued while running it, i'll remove that mention.

**Comment by dolph** [comment]
there's going to be a similar mention in every starter kit that was
supposed to be published with an Android version (4 total?)

**Comment by stevemar** [comment]
@dolph i'm cleaning those up as well. 

@derekteay i removed the mention just now. sorry about the confusion.
